twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        #Variables
        APP_ENV: "%APP_ENV%"
        is_dev_mode: "%is_dev_mode%"
        path_upload_params: "%path_upload_params%"
        #Services
        user_service: "@user_service"
