controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

admin_controllers:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: '/%ADMIN_PATH%'
