# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    ADMIN_PATH: "%env(ADMIN_PATH)%"
    mail.sender: "scandicraft.minecraft@gmail.com"
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    forum_images_url: '/uploads/forum/images/'
    forum_images_directory: '%kernel.project_dir%/public/uploads/forum/images'
    path.spoil.upload_images: /uploads/spoils/images
    VOTE_SERVER_PRIVE_KEY: '%env(VOTE_SERVER_PRIVE_KEY)%'
    APP_ENV: '%env(APP_ENV)%'
    VOTE_DEV_TEST_IP: '%env(VOTE_DEV_TEST_IP)%'
    skins_directory: '%kernel.project_dir%/public/uploads/skins'
    capes_directory: '%kernel.project_dir%/public/uploads/capes'
    path_upload_attachment: /uploads/attachments
    PAYPAL_CLIENT_ID: '%env(PAYPAL_CLIENT_ID)%'
    PAYPAL_SECRET_ID: '%env(PAYPAL_SECRET_ID)%'
    DEDIPASS_PUBLIC_KEY: '%env(DEDIPASS_PUBLIC_KEY)%'
    DEDIPASS_PRIVATE_KEY: '%env(DEDIPASS_PRIVATE_KEY)%'
    rcon_timeout: '%env(rcon_timeout)%'
    rcon_faction_host: '%env(rcon_faction_host)%'
    rcon_faction_port: '%env(rcon_faction_port)%'
    rcon_faction_password: '%env(rcon_faction_password)%'
    STRIPE_SECRET_KEY: '%env(STRIPE_SECRET_KEY)%'
    STRIPE_PUBLIC_KEY: '%env(STRIPE_PUBLIC_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
